### ISSUE TITLE
Use-Alias-Dockerimage: Tag "latest" does not exist

### ISSUE THREAD

**Issue by snapperVibes** [spectrecoin/documentation#1]
[The documentation](https://github.com/aliascash/documentation/wiki/Use-Alias-Dockerimage) says you can use the tag `latest`, but there is no latest tag on the [dockerhub](https://hub.docker.com/r/aliascash/docker-aliaswalletd/tags?page=1&ordering=last_updated). Specifying a version makes the build work correctly.

```
$ docker pull aliascash/docker-aliaswalletd
Using default tag: latest
Error response from daemon: manifest for aliascash/docker-aliaswalletd:latest not found: manifest unknown: manifest unknown
```

**Comment by HLXEasy** [comment]
Thx for reporting! 

I took the chance and migrated the Docker image build to Github actions. So now there's also a `latest` build available.
